### ISSUE TITLE
Inicio

### ISSUE THREAD

**Issue by 05K4R1N** [05K4R1N/Hospital#1]
Hola Daniel :)... pronto te dejo aca  una muestra del Modelado de la BD, dame hasta el miercoles, tu tomate el tiempo si gustas (pero no demasiado :v ) jajajajaja saludos bro.

**Comment by thedanielgray** [comment]
He subido un archivo .SQL con lo que considero un schema suficiente para empezar. Acepto críticas y sugerencias.

**Comment by 05K4R1N** [comment]
![bd](https://cloud.githubusercontent.com/assets/5255678/6141061/b4418210-b176-11e4-8de7-7d3b6abbc954.png) Bueno asi esta la BD segun tu creaste, me tome la molestia de diagramarlo... sin embargo cambie las variables... mi propuesta aca es poner autoincrementables.. esas q sean llaves primarias.. y el codigo hospital, paciente o cuarto sea a parte tmbn.... pienso asi que nos evitariamos de que existan llaves duplicadas( cosa q se q no sucedera o codigos repetidos) pero se que con esto podemos prevenir... que dices bro?

**Comment by 05K4R1N** [comment]
Quisiera saber bro, que version de Postgresql me sugieres?

**Comment by 05K4R1N** [comment]
yo tengo el 9.2 ... esta bien? :+1:

**Comment by thedanielgray** [comment]
Hmmm me parece que creaste columnas IDs duplicadas en algunas tablas. En algunas tablas puede tener sentido que sean autoincrementales (eso en PostgreSQL se implementa con el tipo SERIAL), pero en el segundo punto del enunciado, dice que pueden existir dos cuartos con el mismo código en distintos hospitales (por eso puse la restricción de llave primaria aplicada a ambas columnas en esa tabla).

Respecto a la generación de IDs, los puedes hacer desde la app o desde la BD con SERIAL. Yo los quité para permitir que algún código lo quiera introducir el cliente (tal vez el ID del cuarto). Otra opción es que haya un ID interno único en la tabla, auto-generado, y que haya otro ID seteado por el usuario, debiéndose en ese caso realizar la verificación de no-duplicidad de cuartos en el hospital a nivel de la aplicación.

**Comment by 05K4R1N** [comment]
Si, lo siento, pero el ID de las tablas seria  los autoincrementables, sin embargo el otro que dice hospital_id seria codigo_hospital...  ahora como dice que implementariamos tipo SERIAL en postgres, de acuerdo.. es lo mismo... pero me gustaria mantener en las tablas asi...
id_h serial y codigo_hospital como datos.. el codigo es aparte cuando digamos yo inserte informacion o quiera registrar informacion a mi tabla... hare commit al .sql pero tendra cambios grandes... pero si lo ves necesario tener solo ID ... ok :)

**Comment by thedanielgray** [comment]
No hay problema. Si quieres tener un serial y uno autogenerado no hay
problema. Respecto a la versión de postgresql no tengo ninguna sugerencia.

**Comment by 05K4R1N** [comment]
ya hice commit... me confundi eso ultimo q dces... un serial es un autoincrement asi q no kiero eso... solo quiero un atributo autogenerable eso es todo :) pero si crees que codigo_x x=hospital o x=patient esta bien... al final de cuentas nos datremos cuenta durante el desarrollo de este producto :)

**Comment by 05K4R1N** [comment]
Ah! que IDE usaras? imagino q usaras IntelliJ

**Comment by thedanielgray** [comment]
Un serial es autoincremental, claro.  Atributo autogenerable? Que no sea serial? No entiendo.

Y sí, probablemente usaré IntelliJ.

**Comment by 05K4R1N** [comment]
perdon creo que confundi terminos D:

**Comment by 05K4R1N** [comment]
Perdon me confundi, ... yo usaria netbeans, pero mi temor es que haiga algun conflicto...

**Comment by thedanielgray** [comment]
No me hago lio de usar NetBeans.

**Comment by 05K4R1N** [comment]
Ok, definido:
Administracion de BD: PostgreSQL
IDE: Netbeans
Respecto a la BD quisiera saber tu opinion esta bien tener un dato del tipo Serial y ya no el codigo de tal tabla? o mantenemos como lo puse en las tablas, autoincrementable (ID) y el codigo...

**Comment by thedanielgray** [comment]
Depende como quieres que sea la UI básicamente.

**Comment by 05K4R1N** [comment]
mejor haremos asi: Prueba y error.... en caso de que no me convenza lo que hice mejor sin los codigos... porque la BD de todas formas cambiara conforme se avance con el proyecto...
Daremos inicio con esta BD y si hay algo que no jala nos lo notificamos pues bro... que dices? :)

**Comment by thedanielgray** [comment]
Puede ser... la decisión básicamente es:
Quieres que el código se introduzca manualmente? o no? En el enunciado de tu problema parecía que debía introducirse manualmente. Si quieres hacerlo así, es cuestión de ver si quieres aumentar el autogenerado. A mí me parece adecuado aumentarlo. Dale, a comenzar entonces :)

**Comment by 05K4R1N** [comment]
introducir manualmente el codigo si bro :3 y el autogenerado prefiero mantenerlo tmbn :3 ... veremos a darle start :D

**Comment by thedanielgray** [comment]
Me parece. Dale!
