### ISSUE TITLE
Lograr buenos avances

### ISSUE THREAD

**Issue by 05K4R1N** [05K4R1N/Hospital#2]
bro, si es que en el caso hay otra forma de hacer funcionar algunso algoritmos que voy a implementar y puedes mejorar o alguna operacion te parece mal... aun requerire que me ayudes :3
Triggers tambien si es posible,,,

Cuando puedas bro :)

**Comment by thedanielgray** [comment]
Claro! Eso es back-end :) Revisaré lo que pueda de eso.

**Comment by thedanielgray** [comment]
He corregido la implentación de tu singleton de Conexión para ser thread-safe.

**Comment by 05K4R1N** [comment]
Ok perfecto! ire trabajando en otras funcionalidades todavi.... si habran cambios en la BD igual voy a hacer commits... recuerda que hare ramas por funcionalidad :)

**Comment by 05K4R1N** [comment]
vale bro :)

**Comment by 05K4R1N** [comment]
Ahora si necesito tu ayuda urgente bro... tengo un problema y la verdad un poco me frustro porque no se que pasa por qué no me devuelve bien el resultado, es decir, si selecciono un hospital deberiam ostrarme sus respectivos hospitales... hechale un vistazo al codigo cuandop puedas por fa... el problema esta en que cuando yo selecciono un hospital solo muestra los cuartos del primer hopsitales de la lista del combobox de la clase LookForHospital  y la que yo seleccione no muestra, es decir no muestra los cuartos que corresponden de otro hospital, solo me muestra el primero.
Por fa bro... la BD no fue cambiada para esta funcionalidad.
![lol](https://cloud.githubusercontent.com/assets/5255678/6476318/b3bbe95a-c1ea-11e4-934d-31497a6ae8bd.png)

**Comment by thedanielgray** [comment]
1. El nombre `LookForHospital` indica que no estás armando bien tus clases. Los verbos deberían ir a los métodos, a acciones a realizarse sobre objetos de la clase.
2. Estás llamando a `c_h.getAllHospitalRooms(hospital_name)` 2 veces, una para ver el tamaño (en el método `number_of_HospitalRooms()`) y otra para jalar un elemento de la lista (en el método `getRooms()`). Deberías obtener la lista solamente una vez y hacer tus acciones sobre esa lista obtenida.
3. `c_h` no indica bien el propósito de la variable ni para qué se usa.
4. Sugiero que cambies `number_of_HospitalRooms()` a `numberOfHospitalRooms()` para tener más consistencia en el estilo de casing.

Y finalmente, a priori, viendo el código, me parece que la falla ocurre porque tu `option_rooms` (que es un combobox, por lo cual yo preferiría llamarlo `cmbRooms`) nunca está siendo limpiado de los elementos previos, sino que cada vez que llamas a `getRooms()` sólo le aumentas más y más elementos, por lo que los elementos visibles siempre serán los del primer hospital a pesar de que en realidad sí está leyendo los cuartos correctos.

**Comment by 05K4R1N** [comment]
Colega ya esta refactorizado... puedes ver en la nueva rama creada per directamente ya lo subi al master... chequealo y dime tu opinion... pero verifica todo el codigo de modelo vista y control.... necesito saber si esta todo OK... por favor :)

**Comment by thedanielgray** [comment]
Dale! Estaré fuera del país hasta la siguiente semana, pero a la vuelta lo
reviso.

Pienso que la clase LookForHospital tal vez lo podrías llamar
HospitalSearcher o algo así, para no cambiar mucho tu lógica.

Lo de limpiar los elementos del combobox arregló el problema que estabas
teniendo?

2015-03-09 9:12 GMT-07:00 Oscar Rolando Gamboa A. <notifications@github.com>
:

**Comment by 05K4R1N** [comment]
de hecho no fue lo del combobox sino las instantaciaciones y como enviava los datos a la otra clase ... es decir de `HospitalSearcher` a `addPatient`

**Comment by 05K4R1N** [comment]
Daniel necesito tu ayudaen la clase `Principal.java` necesito saber las acciones que se haran, te explico, esa clase es la ventana principal del proyecto. Ponte como un cliente y dime tu que opciones pondria mas, solo ahi esta puesto que se haria un registro de hospitales, luego Buscar Hospital, dime que otras cosas o acciones mas podría añadir... estoy sin ideas ayuda!

**Comment by 05K4R1N** [comment]
![hospital](https://cloud.githubusercontent.com/assets/5255678/7213644/a46849da-e553-11e4-82f2-1ee2f28873f8.png) que opinas ??

**Comment by thedanielgray** [comment]
1. Los botones están muy pequeños :D 
2. Podrías pensarlo desde el punto de vista no solo del ministerio de salud, sino desde la perspectiva de los hospitales.  Que cada hospital se administre desde su consola separada... pensaría que tener la opción de administrar el hospital desde la consola del ministerio no le concierne. El ministerio estaría más interesado en datos estadísticos a nivel general/macro.

Ahí ya no habría Principal.java sino ConsolaHospital.java y ConsolaMinisterio.java o algo así.

**Comment by 05K4R1N** [comment]
xD ok... mejor retrocedere un poco... el sistema no ira para un Ministerio... tienes razon, en lo que respecta entonces pienso que si debria ir mejor  a un Hospital, estaba pensando asi y de esa manera eliminaria de registro a otros Hospitales puesto a que no tiene sentido que un Hospital registre otros Hospitales.. todo va a enfocado al manejo de un Hospital de hecho :/

**Comment by thedanielgray** [comment]
Hmm un hospital puede tener varias sucursales, entonces registrar un hospital podría tener sentido en algunos casos.

**Comment by 05K4R1N** [comment]
Por el momento eliminare el de Registrar Hospitales. Veremos que hacer luego con las sucursales :)
